config/routes.rb
Rails.application.routes.draw do

  resources :articles
  resources :categories
  resources :guests
  resources :posts
  devise_for :users,
    controllers: {:registrations => "registrations"}
  resources :users

  root 'articles#index'

  get 'comments/create'
  get 'comments/destroy'
  

  resources :articles do
    resources :likes
  end

  resources :articles do
    resources :comments
  end

  resources :posts do
    resources :answers
  end

  resources :answers do
    resources :answers
  end

  resources :users do
    member do
      delete :delete_avatar_attachment
    end
  end

  resources :articles do
    member do
      delete :delete_file
      delete :admin_delete_article
    end
  end

  resources :posts do
    member do
      delete :admin_delete_post
    end
  end


  get 'pages/admin'
  get 'pages/about'

  resources :pages do
    member do
      post:confirm_guest_to_user
      post:refuse_guest
    end
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  belongs_to :category

  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy
  
  has_many_attached :images, dependent: :purge_later
  
  validates :images, presence: true


  def upcase_title
    title = self.title.upcase
  end

  def titleize_title
    title = self.title.titleize
  end

  # display on article#index or the first article images or the cover_img == true if it has one
  def display_cover_img
    @picture = []
    if self.images.any?{|pic| pic.cover_img == true}
      self.images.each do |pic|
        if pic.cover_img == true
          @picture << pic
        end
      end
    else
      @picture << self.images.first
    end
    return @picture.first
  end

  def article_has_like?
    self.likes.count >= 1
  end

  def who_likes_article
    @likes = self.likes.to_a
    @liker = []
    @likes.each do |like|
      @liker << like.user.full_name
    end
    return @liker.join(", ")
  end


end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: %i[ show edit update destroy admin_delete_article]
  before_action :downcase_fields, only: %i[ create update ]
  after_action :define_first_img_as_cover_img, only: %i[ create ]
  #after_action :picture_format, only: %i[ create update ]
  

  # GET /articles or /articles.json
  def index
    if params.has_key?(:category)
      @category = Category.find_by_name(params[:category])
      if Article.where(category: @category).count == 0
        @articles = Article.all.order("created_at DESC")
        flash.now[:notice] = "Aucune création dans la catégorie : #{params[:category]}. Voici l'ensemble des créations"
        params[:category] = nil
      else
        @articles = Article.where(category: @category).order("created_at DESC")
      end
      #@articles = Article.where(category: @category).order("created_at DESC")
    else
      @articles = Article.all.order("created_at DESC")
    end
    # @last_articles = Article.order("created_at DESC").first(2)
  end

  # GET /articles/1 or /articles/1.json
  def show
    @other_articles = Article.where(user_id: @article.user_id).where.not(id: @article.id)
    @images = @article.images.order("created_at ASC")
    @comments = @article.comments.order("created_at ASC")
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
    @images = @article.images.order("created_at ASC")    
  end

  # POST /articles or /articles.json
  def create

    @article = Article.new(article_params)

    if @article.save

      # check if there is ActiveStorage Attachement and if yes get them in @files which is then send to a method to delete files != image, and resize image
      if params[:article][:images].present?
        number_of_ActiveStorage_attachement = params[:article][:images].size
        @files = ActiveStorage::Attachment.where(record_id: @article.id, record_type: 'Article').last(number_of_ActiveStorage_attachement).reverse
        number_of_files_uploaded = @files.length
        @images = upload_file_is_image?(@files)
        number_of_images = @images.length
        if number_of_images > 0
          picture_format(@images)
        end
      end
      
      redirect_to @article
      if number_of_images == 0
        flash[:alert] = "Votre article a été enregistré, cependant les fichiers uploadés ne sont pas au format images. Ils n'apparaîtrons pas"
      elsif number_of_files_uploaded - number_of_images == 1 
        flash[:alert] = "Votre article a été enregistré, cependant 1 fichier uploadé n'est pas au format image. Il n'apparaîtra pas"
      elsif number_of_files_uploaded - number_of_images > 1
        flash[:alert] = "Votre article a été enregistré, cependant #{number_of_files_uploaded - number_of_images}  fichiers uploadés ne sont pas au format image. Ils n'apparaîtront pas"
      else
        flash[:success] = "Votre article a été enregistré !"
      end
    else
      render :new, status: :unprocessable_entity
      flash[:error] = "votre publication n'a pas été enregistrée"
    end

  end

  # PATCH/PUT /articles/1 or /articles/1.json
  def update

    @article.images.each do |image|
      image.cover_img = false
      image.save
    end

    img_id = params[:article][:img_id]

    if img_id != nil 
      attachment = ActiveStorage::Attachment.find(params[:article][:img_id])
      attachment.cover_img = true
      attachment.save
    end
    
    if @article.update(article_params)

      number_of_img_uploaded = 0
      # check if there is ActiveStorage Attachement and if yes get them in @files which is then send to a method to delete files != image, and resize image

      if params[:article][:images].present?
        number_of_ActiveStorage_attachement = params[:article][:images].size
        @files = ActiveStorage::Attachment.where(record_id: @article.id, record_type: 'Article').last(number_of_ActiveStorage_attachement).reverse
      
        #puts "------******************************----------- ------******************************----------- ------******************************-----------"
        # puts "------******************************----------- ------******************************----------- ------******************************-----------"
        # puts "@files : #{@files}" 
        # puts "@files.class : #{@files.class}"
        # puts "------FILES SIZE BEFORE ERASE-----------"
    
 

        # erased no image


        # puts "------FILE SIZE AFTER ERASE-----------"

        numbFiles = @files.length.to_i
        @images = upload_file_is_image?(@files)
        numbImg = @images.length.to_i
        #puts "number_of_images =  : #{numbFiles}"
        number_of_img_uploaded = numbFiles - numbImg
        puts "variable = #{number_of_img_uploaded}"
        # puts "number_of_images : #{number_of_images}"
        #picture_format(@images)
        if @images.length > 0
          picture_format(@images)
        end
      end
      
      puts "variable = #{number_of_img_uploaded}"

      redirect_to @article
      
      if !params[:article][:images].present?
        flash[:success] = "Votre article est bien modifié !"
      elsif numbFiles === numbImg
        flash[:success] = "Votre article est bien modifié !"
      elsif numbFiles != numbImg

        if number_of_img_uploaded == 1
          flash[:alert] = "Votre article a été modifié, cependant 1 fichier uploadé n'est pas au format image. Il n'apparaîtra pas"
        elsif number_of_img_uploaded > 1
          flash[:alert] = "Votre article a été modifié, cependant #{numbFiles - numbImg} fichiers uploadés ne sont pas au format images. Ils n'apparaîtrons pas"
        end

      end

    else
      render :edit, status: :unprocessable_entity
    end
    

  end

  # DELETE /articles/1 or /articles/1.json
  def destroy
    @article.destroy
    redirect_to articles_url
    flash[:success] = "L'article a été supprimé"
  end

  # allow to purge active storage files
  def delete_file
    file = ActiveStorage::Attachment.find(params[:id])
    @article_id = params[:article_id]
    file.purge
    redirect_back(fallback_location: edit_article_path(@article_id))
  end

  def admin_delete_article
    UserMailer.admin_delete_article_email(@article).deliver_now
    @article.destroy
    redirect_to articles_url
    flash[:alert] = "Cette publication a été supprimé. Un email a été envoyé à son créateur pour l'avertir"  
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_article
    @article = Article.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def article_params
    params.require(:article).permit(:title, :description, :user_id, :category_id, images: [])
  end

  def downcase_fields
    article_params[:title].downcase!
  end

  # after_create : set first image as cover image
  def define_first_img_as_cover_img
    if @article.images.count > 0
      attachement = ActiveStorage::Attachment.where(record_id: @article.id, record_type: "Article").first
      attachement.cover_img = true
      attachement.save
    end
  end

  # check if an uploaded file is a image - if not send to be purge - count the number of files purged
  def upload_file_is_image?(files)
    files.each do |file|
      if !file.content_type.start_with? 'image/'
        purge_file(file)
        files.delete file
      end
    end
    return files
  end

  # purge actoive storage attachement
  def purge_file(file)
    file.purge_later
  end


  # if image blob isn't representable convert in appropriate format
  # avoid to get HEIC for e.g. - impossible to get a variant on content_type not true
  def image_blob_is_variable?(images)
    images.each do |image|
      if !image.variable?
        puts "$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$"
        puts "IMAGE NOT VARIABLE"
        puts image.variable?
        blob = image.blob
        puts image.filename
        image.filename = "image"
        puts image.filename
      end

    end
    return images
  end

  # Resize image which whdth or height is superior or equal to my resize_size
  def picture_format(images)
    resize_size = 900
    puts "------******************************-----------"
    puts "------IN PICTURES FORMAT-----------"

    #puts "images.length #{images.length}"
    #puts "images.class #{images.class}"

    #puts "------        -----------"

      images.each do |image|
        meta = ActiveStorage::Analyzer::ImageAnalyzer.new(image).metadata
        #puts "image : #{image}"
        #puts "image.class : #{image.class}"
        if meta[:width] >= resize_size || meta[:height] >= resize_size   
          blob = image.blob
          #puts "blob : #{blob}"
          #puts "blob.class : #{blob.class}"
          blob.open do |picture|
            #puts pic
            #puts pic.class
            #puts pic.path


            ImageProcessing::MiniMagick.source(picture.path)
              .resize_to_limit(resize_size, resize_size)
              .quality(80)
              .call(destination: picture.path) #picture seulement marche aussi
            new_data = File.binread(picture.path)
            @article.send(:images).attach io: StringIO.new(new_data), filename: blob.filename.to_s, content_type: 'image'
            image.purge
          end
        end

      end
    



        # blob.open do |picture|
        #   puts "------PICTURES PATH -----------"
        #   path = picture.path
        #   puts picture.path
        #   ImageProcessing::MiniMagick.source(path)
        #     .resize_to_limit(1200, 1200)
        #     .call(destination: path)
        #   new_data = File.binread(path)
        #   @article.send(:images).attach io: StringIO.new(new_data), filename: blob.filename.to_s, content_type: 'image'
        #   puts "----------------------------------"
        # end
        #image.purge_later 

        # blob.open do |temp_file| # temp_file
        #   path = temp_file.path #temp_file

app/helpers/articles_helper.rb
module ArticlesHelper

  # return a centered crop landscape picture if picture is portrait
  def crop_portrait_post_picture(image)
    # return true if picture mode is portrait (heigth > width )
    width = image.blob.metadata[:width].to_i
    height = image.blob.metadata[:height].to_i
    if  width < height
      return image.variant(resize: "300x225^", gravity: "center", crop: "300x225+0+0")
    else 
      return image
    end   
  end

end

app/views/articles/_carousel.html.erb
<% if @article.images.count == 1 %>
    <%= image_tag @article.images.first, :width=>600, :crop=>"fill", class: "img-fluid" %>
<% elsif @article.images.attached? && @article.images.count > 1 %>
 <div id="myCarousel" class="carousel slide" data-bs-ride="carousel">

    <div class="carousel-indicators">
      <% @article.images.each_with_index do |image, index| %>
        <button type="button" data-bs-target="#myCarousel" data-bs-slide-to=<%= index %> class="<%= "active" if index.zero? %>" aria-current="true" aria-label="Slide 1"></button>
      <% end %>
    </div>

    <div class="carousel-inner">
      <% @article.images.each_with_index do |image, index| %>
        <div class="carousel-item <%= "active" if index.zero? %>">
          <img class="bd-placeholder-img" width="100%" height="100%" src="<%=  image_path(url_for(image)) %>"aria-hidden="true" preserveAspectRatio="xMidYMid slice" focusable="false">
          <!-- ORIGINAL CARROUSSEL WITH ALL THE INFO : LINKS OVER THE PICTURE - COULD BE A FEATURES 
          <div class="container">
            <div class="carousel-caption text-start">
              <h1>Example headline.</h1>
              <p>Some representative placeholder content for the first slide of the carousel.</p>
              <p><a class="btn btn-lg btn-primary" href="#">Sign up today</a></p>
            </div>
          </div>
          -->
        </div>
      <% end %>
    </div>
    
    <button class="carousel-control-prev" type="button" data-bs-target="#myCarousel" data-bs-slide="prev">
      <span><i class="fas fa-3x fa-arrow-circle-left"></i></span>
      <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#myCarousel" data-bs-slide="next">
      <span><i class="fas fa-3x fa-arrow-circle-right"></i></span>
      <span class="visually-hidden">Next</span>
    </button>
    
  </div>
<% end %>

    

app/views/articles/_comments.html.erb
  <% @comments.each do |comment| %>
    <% unless !comment.persisted? %>
      <div class="comment">

        <div class="dark-plum">
            <%= comment.user.full_name %> : <span class="comment-body"><%= comment.body %></span>
        </div>
        
        <div class="d-flex justify-content-start comment-info">
          <div><span class="">il y a <%= time_ago_in_words(comment.created_at) %></span></div>
          <% if comment.user.id == current_user.id%>
            <div class="">
              <%= link_to [comment.article, comment], class: "hover", method: :delete, data: { confirm: 'Êtes vous sûr de vouloir supprimer votre commentaire ?' } do %>
                <span class="delete-btn">supprimer mon commentaire</span>
              <% end %>
            </div>
          <% end %>
        </div>
      </div>
    <% end %>
  <% end %>

app/views/articles/_form.html.erb
<%= form_with(model: @article) do |form| %>
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@article.errors.count, "erreur") %> empêchent cet article d'être enregistré:</h2>

      <ul>
        <% @article.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= simple_form_for(@article) do |f| %>

    <div class="form-inputs">

      <%= f.hidden_field :user_id, :value => current_user.id %>
      <div class="mb-2">
        <p class="text">Catégorie de votre création :</p>
        <%= f.select :category_id, Category.pluck(:name, :id), :include_blank => 'choississez une categorie' %>
      </div>
      <div>
        <%= f.input :title, label: 'Titre', input_html: {class: 'input text mb-2'}, required: true, wrapper: false, label_html: {class: 'label mb-1'} %>
      </div>
      <%= f.input :description, input_html: {class: 'textarea mb-2', :rows => 15}, required: true, wrapper: false, label_html: {class: 'label mb-1'} %>
      
      <% if @article.images.count > 1 %>
        <p class="text">Ajoutez d'autres photos :</p>
      <% else %>
        <p class="text">Ajoutez une ou plusieurs images (vous pouvez sélectionner plusieurs photos en même temps) :</p>
      <% end %>
      <%= f.file_field :images, multiple:true, direct_upload: true, class: "form-control mt-2 mb-2" %>

      <br>
      <p class="text">Parmi les images déjà téléchargées choississez laquelle sera l'image principale, celle utiliser pour présenter votre créations</p>
      <% if @article.images.attached? %>
        <div class="row mb-2">
          <% @images.each do |image| %>
            <div class="col-6 col-xs-6 col-sm-6 col-md-4 col-lg-4 col-xl-4">
                <div class="card-edit-img">
                  <div class="card-content">
                    <%= image_tag image, class: "img-fluid mb-2" %> 
                    <div class="d-flex flex-column align-items-center img-data">
                      <div>
                        <span><%= f.radio_button:img_id, image.id, :checked => (image.cover_img == true), required: true  %> image principale</span><br>
                      </div>
                      <div>
                        <span><%= link_to 'supprimer', delete_file_article_path(image.id, article_id: @article.id), method: :delete, class: 'delete-img', confirm: 'Êtes vous certain de vouloir supprimer cette image ?'  %></span>
                      </div>
                      <div>
                        <%= image.variable? %>
                      </div>
                    </div>
                  </div>
                </div>
            </div>
          <% end %>
        </div>
      <% end %>


    </div>

    <div class="form-actions mb-2">
      <%= f.button :submit, 'valider', class: "btn-light-pink" %>
    </div>
  <% end %>

<% end %>

app/views/articles/edit.html.erb
<div class="container main-wrapper">
  <h1>Mettre à jour mon article</h1>

  <%= render 'form', article: @article %>



      <%= link_to 'Annuler', @article,  class: 'btn-dark-back mb-2' %> 


</div>

app/views/articles/index.html.erb
<div class="container main-wrapper">

  <h1>Créations</h1>

  <hr>

  <% if params[:category] == nil %>
    <%= link_to 'Tout', articles_path, class: "filter-article-active" %>
  <% else %>
    <%= link_to 'Tout', articles_path, class: "filter-article" %>
  <% end %>

  <% Category.all.order("name ASC").each do |cat| %>
    <% if params[:category] == cat.name %>
      <%= link_to cat.name.capitalize, articles_path(category: cat.name), class: "filter-article-active" %>
    <% else %>
      <%= link_to cat.name.capitalize, articles_path(category: cat.name), class: "filter-article" %>
    <% end %>
  <% end %>

  <hr>

  <div class="row">
    <% @articles.each do |article| %>
    
    <div class="col-xs-12 col-sm-6 col-md-6 col-lg-4 col-xl-3">

      <%= link_to (article) do %>

        <div class="card">

          <div class="card-content">

            <!-- COVER IMG -->
            <% if article.images.attached? %>
              <div class="card-img-top">
                <%= image_tag crop_portrait_post_picture(article.display_cover_img), class: "img-fluid" %>
              </div>
            <% end %> 

            <div class="card-body">
              <h5 class="card-title"><%= article.title.capitalize %></h5>
              <div class="article-user">
                <%= article.user.full_name %>
              </div>
              <!-- -->
              <div class="card-text">
                <div class="mb-2">
                  publié le <%= l(article.created_at, format: :date) %>
                </div>
                <div>
                  <span class="article-badge-full"><%= article.category.name %></span>
                  <% if article.likes.count > 0 %>
                    <span class="social-badge"><i class="fas fa-heart info-icon"></i><%= article.likes.count %></span>
                  <% end %>
                  <% if article.comments.count > 0 %>
                    <span><i class="far fa-comment-alt"></i><%= article.comments.count %></span>
                  <% end %>
                </div>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
    <% end %>
  </div>
</div>

app/views/articles/new.html.erb
<div class="container main-wrapper">
  <h1>Nouvelle Création</h1>

  <%= render 'form', article: @article %>

  <%= link_to 'Back', articles_path %>
</div>

app/views/articles/show.html.erb
<div class="container main-wrapper">

  <!-- ARTICLE -->

  <header>
    <h1><%= @article.upcase_title %></h1>
    <div class="d-flex justify-content-start">
      <% if @article.user.avatar.attached? %>
        <div class="post-avatar">
          <%= image_tag @article.user.avatar.variant(resize_to_limit: [70, 70]), class: "rounded-circle" %>
        </div>
      <% end %>
      <div>
        <h3 class="text">création de <strong><%= @article.user.full_name %></strong></h3>   
        <div class="text article-data">
          publié le <%= l(@article.created_at, format: :date) %>
        </div>
        <div class="text d-flex justify-content-start">
          <div class="article-badge-full"><%= @article.category.name %></div>
          <% if user_signed_in? %>
            <% if @article.comments.count > 0 %>
              <div class="article-data">
                <span><i class="fas fa-comment-alt info-icon"></i><%= @article.comments.count %></span>
              </div>
            <% end %>
            <% if @article.article_has_like? %>
              <div class="article-data">
                <span data-bs-toggle="tooltip" data-bs-placement="right" title="<%= @article.who_likes_article %>"><i class="fas fa-heart info-icon"></i><%= @article.likes.count %></span>
              </div>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
  </header>

  <!-- IMAGES CAROUSEL -->

  <article>
    <%= render 'carousel', article: @article %>
  </article>

  <!-- DESCRIPTION -->

  <article>
    <h3>Description</h3>
    <div class="text">
      <%= @article.description %>
    </div>
  </article>

  <!-- ACTION ZONE -->

  <article>
  <hr>
    <% if user_signed_in? %>
      <div class="article-action d-flex justify-content-around">
        <div>
          <%= button_to article_likes_path(@article), :title => 'liker', class: "no-btn", method: :post do %>
            <i class="far fa-heart action-icon"></i><span class="dark-color d-none d-sm-none d-md-none d-lg-inline d-xl-inline">j'aime</span>
          <% end %>
        </div>

        <% if current_user.id != @article.user.id %>
          <div>
            <%= button_to user_path(@article.user_id), :title => 'profil', class: "no-btn", method: :get do %>
              <i class="far fa-user action-icon"></i><span class="dark-color d-none d-sm-none d-md-none d-lg-inline d-xl-inline">profil de <%= @article.user.first_name.capitalize %></span>
            <% end %>
          </div>
        <% end %>
        
        <% if current_user.id == @article.user.id %>

          <div>
            <%= button_to edit_article_path(@article), :title => 'modifier ma publication', class: "no-btn", method: :get do %>
              <i class="far fa-edit action-icon"></i><span class="dark-color d-none d-sm-none d-md-none d-lg-inline d-xl-inline">modifier ma publication</span>
            <% end %>
          </div>
          
          <div>
            <%= button_to @article, class: "no-btn", :title => 'supprimer ma publication', method: :delete, data: { confirm: 'Êtes vous certain de vouloir supprimer cet article ?' } do %>
              <i class="far fa-trash-alt action-icon"></i><span class="dark-color d-none d-sm-none d-md-none d-lg-inline d-xl-inline">supprimer ma publication</span>
            <% end %>
          </div>

        <% end %>
      </div>
      <hr>
    <% end %>
  </article>
  
  <!-- COMMENT -->

  <% if user_signed_in? %>
    <article>
      <h3><%= (@article.comments.count) < 2 ? 'Commentaire' : 'Commentaires'%></h3>

      <!-- DISPLAY COMMENT -->
      <%= render 'comments' %>

      <!-- NEW COMMENT -->
      <div>
        <div>
          <%= form_with(model: [@article, @article.comments.build]) do |f| %>
              <%= f.hidden_field :user_id, value: current_user.id %>
            <div class="form-group col-12">
              <div id="post-index-title-wrapper">
              <%= f.text_area :body, class: 'form-control', required: true %></a>
            </div>
            <%= button_tag type: 'submit', class: "no-btn" do %>
              <i class="far fa-comment-alt"></i><span>je commente</span></i>
            <% end %>
          <% end %>
        </div>
      </div>
    </article>
  <% end %>

  <!-- ADMIN SECTION -->

  <% if user_signed_in? && current_user_is_admin? && current_user.id != @article.user.id %>
    <article>
      <div class="card-admin">
        <div class="d-flex justify-content-center">
          <div class="admin-content">
            <h3 class="dark-color d-none d-sm-none d-md-none d-lg-inline d-xl-inline">Section administrateur</h3>
          </div>
          <div class="admin-content">
            <%= link_to 'Supprimer cette publication', admin_delete_article_article_url(@article), class:"btn btn-outline-danger", method: :delete, data: { confirm: "Êtes vous certain de vouloir supprimer cette publication. Un email sera envoyé au membre afin de l'avertir de cette suppression" } %> 
          </div>
        </div>
        <div class="d-flex justify-content-center">
          <p class="dark-color d-none d-sm-none d-md-none d-lg-inline d-xl-inline">
            En tant qu'administrateur vous pouvez supprimer une publication si vous jugez son contenu inapropriété. <i class="fas fa-exclamation-triangle"></i> Cette action est irréversible !
          </p>
        </div>
      </div>
    </article>
  <% end %>


  <!-- OTHER USER ARTICLE -->

  <% if @article.user.articles.count > 1 %>
    <article>
      <h3><%= (@article.user.articles.count) > 2 ? 'Autres créations' : 'Autre création'%> de <%= @article.user.first_name.capitalize%></h3>

      <div class="row">
        <% @other_articles.each do |article| %>
          <div class="col-6 col-sm-6 col-md-4 col-lg-3 col-xl-3">
              <%= link_to (article) do %>
                <div class="card-small">
                  <% if article.images.attached? %>
                    <div class="card-img-top mb-1">
                      <%= image_tag crop_portrait_post_picture(article.display_cover_img), class: "img-fluid" %> 
                    </div>
                  <% end %>
                  <div class="card-body">
                    <h5><%= article.title.capitalize %></h5>
                    <div class="card-text">
                      <div class="mb-2">
                        publié le <%= l(article.created_at, format: :date) %>
                      </div>
                      <div>
                        <span class="article-badge-full"><%= article.category.name %></span>
                        <% if article.comments.count > 0 %>
                          <span><i class="fas fa-comment-alt info-icon"></i><%= article.comments.count %></span>
                        <% end %>
                        <% if article.likes.count > 0 %>
                          <span class="social-badge"><i class="fas fa-heart info-icon"></i><%= article.likes.count %></span>
                        <% end %>
                      </div>
                    </div>
                  </div>
                </div>
              <% end %>
            </div>
        <% end %>
      </div>
    </article>
  <% end %>

</div><!-- END OF CONTAINER -->








 