config/routes.rb
Rails.application.routes.draw do

  resources :articles
  resources :categories
  resources :guests
  resources :posts
  devise_for :users,
    controllers: {:registrations => "registrations"}
  resources :users

  root 'articles#index'

  get 'comments/create'
  get 'comments/destroy'
  

  resources :articles do
    resources :likes
  end

  resources :articles do
    resources :comments
  end

  resources :posts do
    resources :answers
  end

  resources :answers do
    resources :answers
  end

  resources :users do
    member do
      delete :delete_avatar_attachment
    end
  end

  resources :articles do
    member do
      delete :delete_file
      delete :admin_delete_article
    end
  end

  resources :posts do
    member do
      delete :admin_delete_post
    end
  end


  get 'pages/admin'
  get 'pages/about'

  resources :pages do
    member do
      post:confirm_guest_to_user
      post:refuse_guest
    end
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :articles, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :posts, dependent: :destroy
  has_many :answers, dependent: :destroy

  has_one_attached :avatar, dependent: :purge_later
  
  def full_name
    full_name = [first_name.capitalize, last_name.capitalize].join(' ')
  end

  def guest_request?
    Guest.all.count != 0
  end

  def user_pluralize_article
    num = self.articles.count
    num > 1 ? "#{num} creations" : "#{num} creation"
  end

  def user_pluralize_post
    num = self.articles.count
    num > 1 ? "#{num} annonces" : "#{num} annonce"
  end

  def user_publishing
    @articles = self.articles
    @posts = self.posts

    @creation = "#{@articles.count} création".pluralize if @articles.count != 1
    @annonce = @posts.count != 1 ? "#{@posts.count} annonces" : "#{@posts.count} annonce"
    
    "#{} annonce"

    if @articles.count == 0 && @posts.count == 0
      return "aucune publication"
      
    elsif @articles.count > 0 && @posts.count == 0
      return @creation.to_s

    elsif @articles.count == 0 && @posts.count > 0
      return @annonce.to_s

    elsif @articles.count > 0 && @posts.count > 0
      return "#{@creation} et #{@annonce}"
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  include UsersHelper
  
  before_action :set_user, only: %i[ show edit update destroy ]
  before_action :downcase_fields, only: %i[ create update ]

  # GET /users or /users.json
  def index

    @users = User.all.order("first_name ASC")

    if params[:order] == 'name'
        @users = User.all.order("first_name ASC")
    elsif params[:order] == 'lastname'
        @users = User.all.order("last_name ASC")
    else
      @users = User.all.order("first_name ASC")
    end

  end

  # GET /users/1 or /users/1.json
  def show
    @articles = @user.articles.order("created_at DESC")
    @posts = @user.posts.order("created_at DESC")
    @guests = Guest.all.order("first_name ASC")
    @last_articles = Article.limit(2).order("created_at DESC")
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: "Vos modififications ont bien été enregistrées" }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def delete_avatar_attachment
    @image = ActiveStorage::Attachment.find(params[:id])
    @image.purge
    redirect_back(fallback_location: request.referer)
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:first_name, :last_name, :phone_number, :email, :avatar, :show_data)
    end

    # downcase some fields before saving in db
    def downcase_fields
      user_params[:first_name].downcase!
      user_params[:last_name].downcase!
      user_params[:email].downcase!
    end

end

app/helpers/users_helper.rb
module UsersHelper

  def current_user_is_admin?
    current_user.is_admin == true
  end

  # display user.avatar or a defult one if he hasn't one
  def avatar_for(user)
    user.avatar.attached? ? user.avatar : asset_path("default-avatar.jpg")
  end
 


end

app/views/users/_createuser.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>


  <div class="form_group">
    <%= form.label :prénom %>
    <%= form.text_field :first_name, required: true, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :nom %>
    <%= form.text_field :last_name, required: true, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :email %>
    <%= form.text_field :email, required: true, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :téléphone %>
    <%= form.text_field :phone_number, class: "form-control" %>
  </div>

  <div class="field">
    <%= form.hidden_field :password, :value => "000000" %>
  </div>

  <div class="field">
    <%= form.hidden_field :show_data, :value => true %>
  </div>

  <div class="form-group">
    <%= form.label :show_data, "Afficher les coordonnées" %><br>
    <%= form.label :show_data, "oui", :value => "true"  %>
    <%= form.radio_button :show_data, true %>
    <%= form.label :show_data, "non", :value => "false" %>
    <%= form.radio_button :show_data, false %>
    <p>permet de rendre visible aux autres utilisateurs le numéro de téléphone et l'email dans l'annuaire</p>
  </div>
  
  <div class="actions mt-2">
    <%= form.submit 'Enregistrer le nouveau membre' %>
  </div>

<% end %>

app/views/users/_currentuser.html.erb
<div class="card-user-profil">

  <div class="d-flex flex-row">

    <div class="p-2">
      <%= image_tag avatar_for(@user), style: "width: 100px; display: block", class: "rounded-circle" %>
    </div>

    <div class="p-2">
      <div>
        <h3>Mon espace</h3>
        <span class="">membre depuis le <%= l(@user.created_at, format: :date) %></span><br>
        <span class="">vous avez publié <%= @user.user_pluralize_article %> et <%= @user.user_pluralize_post %></span>
      </div>
      <hr>
      <div>
         <div class="d-flex justify-content-around">
            <div>
              <%= button_to edit_user_path(@user), :title => 'modifier mon profil', class: "no-btn", method: :get do %>
                <i class="far fa-edit action-icon"></i><span class="d-none d-sm-none d-md-none d-lg-inline d-xl-inline">modifier mon profil</span>
              <% end %>
            </div>

            <div>
              <%= button_to new_article_path, :title => 'nouvelle création', class: "no-btn", method: :get do %>
                <i class="fas fa-plus-circle action-icon"></i></i><span class="d-none d-sm-none d-md-none d-lg-inline d-xl-inline">nouvelle création</span>
              <% end %>
            </div>

            <div>
              <%= button_to new_post_path, :title => 'nouvelle annonce', class: "no-btn", method: :get do %>
                <i class="far fa-plus-square action-icon"></i><span class="d-none d-sm-none d-md-none d-lg-inline d-xl-inline">nouvelle annonce</span>
              <% end %>
            </div>
          </div>
      </div>

    </div>
  </div>

</div>

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>


  
  <div>
    <%= image_tag avatar_for(user), style: "width: 150px; display: block", class: "rounded-circle" %>
    <br>
    <br>
    <%= form.file_field :avatar, direct_upload: true %>
  </div>

  <br>

  <div class="form_group">
    <%= form.label :prénom %>
    <%= form.text_field :first_name, required: true, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :nom %>
    <%= form.text_field :last_name, required: true, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :téléphone %>
    <%= form.text_field :phone_number, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :email %>
    <%= form.text_field :email, required: true, class: "form-control" %>
  </div>

  <div class="field">
    <%= form.hidden_field :password, :value => "000000" %>
  </div>

  <div class="field">
    <%= form.hidden_field :show_data, :value => true %>
  </div>

  <div class="form-group">
    <%= form.label :show_data, "Afficher mes coordonnées" %><br>
    <%= form.label :show_data, "oui", :value => "true"  %>
    <%= form.radio_button :show_data, true %>
    <%= form.label :show_data, "non", :value => "false" %>
    <%= form.radio_button :show_data, false %>
    <p>permet de rendre visible aux autres utilisateurs votre numéro de téléphone et email dans l'annuaire</p>
  </div>
  
  <div class="actions mt-2">
    <%= form.submit 'modifier mon profil'  %>
  </div>

<% end %>

app/views/users/_user.html.erb
<div class="card-user-profil">

  <div class="d-flex flex-row">
    <div class="p-2">
      <%= image_tag avatar_for(@user), style: "width: 100px; display: block", class: "rounded-circle" %>
    </div>
    <div class="p-2">
      <div>
        <h3><small> profil de : </small><%= @user.full_name %></h3>
        <span class="">membre depuis le <%= l(@user.created_at, format: :date) %></span><br>
        <%= @user.user_publishing %> 
      </div>
    </div>
  </div>

</div>

app/views/users/edit.html.erb
<div class="container">
  <h1>Modifier mon profil</h1>

  <%= render 'form', user: @user %>

  <%= link_to 'Show', @user %> |
  <%= link_to 'Back', users_path %>
</div>

app/views/users/index.html.erb
<div class="container main-wrapper">

  <h1>Annuaires des membres</h1>

  <article>
    <table id="user-index"class="table text">
      <thead class="thead">
        <tr>
          <th scope="col"></th>
          <th scope="col"><%= link_to "Prénom", users_path(order: 'name') %></th>
          <th scope="col"><%= link_to "Nom", users_path(order: 'lastname') %></th>
          <th scope="col">Email</th>
          <!--
          <th scope="col">Téléphone</th>
          <th scope="col">Publication</th>
          -->
        </tr>
      </thead>
      <tbody>
        <% @users.each do |user| %>
          <tr onmouseover="this.style.cursor='pointer';" onclick="location.href='<%= url_for(user) %>';">
            <td><%= image_tag avatar_for(user), style: "width: 25px; display: block", class: "avatar-book rounded-circle" %></td>
            <td><%= user.first_name.capitalize %></td>
            <td><%= user.last_name.capitalize %></td>
            <td><%= user.email if user.show_data == true %></td>
            <!--
            <td><%= user.phone_number if user.show_data == true %></td>
            <td><%= user.user_publishing %></td>
            -->
          </tr>
        <% end %>
      </tbody>
    </table>
</article>

</div>

app/views/users/new.html.erb
<div class="container">
  <h1>Enregistrer un nouveau membre</h1>

  <p>
  en tant qu'administrateur vous créer le compte de nouveau membre. Veuillez compléter les champs obligatoire. Une fois valider le nouveau membre sera notifié par email de la création de son espace.
  Un lien l'invitera a créer son mot de passe afin de rendre son compte entièrement opérationnel.
  </p>
  

  <%= render 'createuser', user: @user %>

  <%= link_to 'Back', users_path %>
</div>

app/views/users/show.html.erb
<div class="container main-wrapper">

  <!-- USER INFO -->
  <div>
    <% if user_signed_in? && current_user.id == @user.id %>
      <%= render "users/currentuser" %>
    <% else %>
      <%= render "users/user" %>
    <% end %>
  </div>

  <!-- ADMIN SECTION - NEW REQUEST -->

  <% if user_signed_in? && current_user_is_admin? && @user.id == current_user.id %>

    <% if is_member_request? %>
      <h3>Nouvelle demande de membre</h3>
      <div class="card-admin">
        <table class="request-table">
          <thead>
            <tr>
              <th>prénom</th>
              <th>nom</th>
              <th>email</th>
              <!--
              <th>téléphone</th>
              -->
              <th></th>
            </tr>
          </thead>
          <% @guests.each do |guest| %>
            <tbody>
              <tr>
                <td style="min-width:15%"><%= guest.first_name.capitalize %></td>
                <td style="min-width:15%"><%= guest.last_name.capitalize %></td>
                <td style="min-width:20%"><%= guest.email %></td>
                <!--
                <td style="min-width:20%"><%= guest.phone_number %></td>
                -->
                <td>
                  <div class="d-flex flex-row">
                    <div>
                      <%= button_to confirm_guest_to_user_page_path(guest.id), class: "btn btn-outline-primary social-badge", params: { admin: current_user.id }, method: :post do %>
                        <i class="fas fa-check action-icon"></i><span class="d-none d-sm-none d-md-none d-lg-inline d-xl-inline">Accepter</span>
                      <% end %>
                    </div>
                    <div>
                      <%= button_to refuse_guest_page_path(guest.id), class: "btn btn-outline-danger", params: { admin: current_user.id }, data: { confirm: 'Êtes vous certain de vouloir refuser cette demande ?' }, method: :post do %>
                        <i class="fas fa-times action-icon"></i><span class="d-none d-sm-none d-md-none d-lg-inline d-xl-inline">Refuser</span>
                      <% end %>
                    </div>
                  </div>
                </td>
              </tr>
            </tbody>
          <% end %>
        </table>
      </div>
    <% end %>
  <% end %>

  <!-- ADMIN SECTION - ADMIN ADD NEW MEMBER -->
  <% if user_signed_in? && current_user_is_admin?  && @user.id == current_user.id %>
    <div class="card-admin">
      <div class="d-flex justify-content-center">
        <div class="admin-content">
          <%= button_to new_user_path, class: "btn btn-outline-primary social-badge", method: :get do %>
            <span>Enregister un nouveau membre</span>
          <% end %>
        </div>
      </div>
      <div class="d-flex justify-content-center">
        <p class="d-none d-sm-none d-md-none d-lg-inline d-xl-inline">
          En tant qu'administrateur vous pouvez enregister un nouveau membre.
        </p>
      </div>
    </div>
  <% end %>
  

  <!-- RENDER USER ARTICLE AND POST -->

  <div class="container-fluid">
    <% if @user.articles.count == 0 && @user.posts.count == 0 %>
      <%= render "users/user_publishing/no-publishing" %>
    <% elsif @user.articles.count >= 1 && @user.posts.count == 0 %>
      <%= render "users/user_publishing/article-no-post" %>
    <% elsif @user.articles.count == 0 && @user.posts.count >= 1 %>
      <%= render "users/user_publishing/no-article-post" %>
    <% elsif @user.articles.count >= 1 && @user.posts.count >= 1 %>
      <%= render "users/user_publishing/article-and-post" %>
    <% end %>
  </div>



  <!-- ADMIN SECTION - DATA -->

  <% if user_signed_in? && current_user_is_admin? && @user.id == current_user.id %>
    <div class="card-admin">
      <p class="data">il y a <%= number_of_members %> membres |  <%= number_of_articles %> créations |  <%= number_of_posts %> annonces<br>
      soit une moyenne de <%= average_article_per_member %> créations postées par membres
      </p>
    </div>
  <% end %>


</div>