config/routes.rb
Rails.application.routes.draw do

  resources :articles
  resources :categories
  resources :guests
  resources :posts
  devise_for :users,
    controllers: {:registrations => "registrations"}
  resources :users

  root 'articles#index'

  get 'comments/create'
  get 'comments/destroy'
  

  resources :articles do
    resources :likes
  end

  resources :articles do
    resources :comments
  end

  resources :posts do
    resources :answers
  end

  resources :answers do
    resources :answers
  end

  resources :users do
    member do
      delete :delete_avatar_attachment
    end
  end

  resources :articles do
    member do
      delete :delete_file
      delete :admin_delete_article
    end
  end

  resources :posts do
    member do
      delete :admin_delete_post
    end
  end


  get 'pages/admin'
  get 'pages/about'

  resources :pages do
    member do
      post:confirm_guest_to_user
      post:refuse_guest
    end
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :answerable, polymorphic: true
  has_many :answers, as: :answerable, dependent: :destroy
  
  belongs_to :user

  validates_presence_of :body
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  belongs_to :category

  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy
  
  has_many_attached :images, dependent: :purge_later
  
  validates :images, presence: true


  def upcase_title
    title = self.title.upcase
  end

  def titleize_title
    title = self.title.titleize
  end

  # display on article#index or the first article images or the cover_img == true if it has one
  def display_cover_img
    @picture = []
    if self.images.any?{|pic| pic.cover_img == true}
      self.images.each do |pic|
        if pic.cover_img == true
          @picture << pic
        end
      end
    else
      @picture << self.images.first
    end
    return @picture.first
  end

  def article_has_like?
    self.likes.count >= 1
  end

  def who_likes_article
    @likes = self.likes.to_a
    @liker = []
    @likes.each do |like|
      @liker << like.user.full_name
    end
    return @liker.join(", ")
  end


end

app/models/category.rb
class Category < ApplicationRecord
  has_many :articles
end

app/models/column.rb
class Column < ApplicationRecord
  has_many :posts
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
  belongs_to :user
  #validates :body, presence :true

  def comment_time
    time = Time.now
    date = self.created_at
    if time.year == date.year
      I18n.localize Date.today, format: :short
    else
      self.created_at
    end
  end

end

app/models/guest.rb
class Guest < ApplicationRecord
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :article
  belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  belongs_to :column

  has_one_attached :picture, dependent: :purge_later

  has_many :answers, as: :answerable, dependent: :destroy

  validates :title, presence: true
  validates :body, presence: true



  def display_created_at
    create = created_at.strftime("%d %B %Y")
  end

  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :articles, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :posts, dependent: :destroy
  has_many :answers, dependent: :destroy

  has_one_attached :avatar, dependent: :purge_later
  
  def full_name
    full_name = [first_name.capitalize, last_name.capitalize].join(' ')
  end

  def guest_request?
    Guest.all.count != 0
  end

  def user_pluralize_article
    num = self.articles.count
    num > 1 ? "#{num} creations" : "#{num} creation"
  end

  def user_pluralize_post
    num = self.articles.count
    num > 1 ? "#{num} annonces" : "#{num} annonce"
  end

  def user_publishing
    @articles = self.articles
    @posts = self.posts

    @creation = "#{@articles.count} création".pluralize if @articles.count != 1
    @annonce = @posts.count != 1 ? "#{@posts.count} annonces" : "#{@posts.count} annonce"
    
    "#{} annonce"

    if @articles.count == 0 && @posts.count == 0
      return "aucune publication"
      
    elsif @articles.count > 0 && @posts.count == 0
      return @creation.to_s

    elsif @articles.count == 0 && @posts.count > 0
      return @annonce.to_s

    elsif @articles.count > 0 && @posts.count > 0
      return "#{@creation} et #{@annonce}"
    end
  end

end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper

  # return a centered crop landscape picture if picture is portrait
  def crop_portrait_post_picture(image)
    # return true if picture mode is portrait (heigth > width )
    width = image.blob.metadata[:width].to_i
    height = image.blob.metadata[:height].to_i
    if  width < height
      return image.variant(resize: "300x225^", gravity: "center", crop: "300x225+0+0")
    else 
      return image
    end   
  end

end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/columns_helper.rb
module ColumnsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/guests_helper.rb
module GuestsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/pages_helper.rb
module PagesHelper

  def is_member_request?
    Guest.all.count != 0
  end


  def number_of_members
    User.all.count
  end

  def number_of_articles
    Article.all.count
  end

  def number_of_posts
    Post.all.count
  end

  def average_article_per_member
    average = self.number_of_articles.to_f / self.number_of_members.to_f
    return num = average.round(2)
  end

end

app/helpers/posts_helper.rb
module PostsHelper

  # return a centered crop landscape picture if picture is portrait
  def crop_portrait_post_picture(image)
    # return true if picture mode is portrait (heigth > width )
    width = image.blob.metadata[:width].to_i
    height = image.blob.metadata[:height].to_i
    if  width < height
      return image.variant(resize: "300x225^", gravity: "center", crop: "300x225+0+0")
    else 
      return image
    end   
  end

end

app/helpers/users_helper.rb
module UsersHelper

  def current_user_is_admin?
    current_user.is_admin == true
  end

  # display user.avatar or a defult one if he hasn't one
  def avatar_for(user)
    user.avatar.attached? ? user.avatar : asset_path("default-avatar.jpg")
  end
 


end

app/views/layouts/_flash.html.erb
<% if flash.any? %>
  <% flash.each do |type, msg| %>
    <div id="flash-<%= type %>" class="alert <%= bootstrap_class_for_flash(type) %> alert-dismissible fade show" role="alert">
      <div class="container flash-alert d-flex justify-content-between">
        <div>
          <%= msg %>
        </div>
        <div>
          <button type="button" class="no-btn" data-bs-dismiss="alert" aria-label="Close">
            <span aria-hidden="true"><i class="fas fa-times"></i></span></button>
        </div>
      </div>
    </div>
    <script>setTimeout(e => document.getElementById("flash-<%= type %>").remove(), 5000);</script> 
  <% end %>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="bg-gray-dark">
  <div class="container">

    <p class="m-0">Renov-Fauteuil - club Chevry</p>
    <%= image_tag('renov-fauteuil-logo-cream.png', width: '55', alt: "logo") %>
  </div>
</footer>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark dark-plum-back">
  <div class="container-fluid">
    <div><%= link_to "Renov-Fauteuil", root_path, :class => "navbar-brand" %></div>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">

        <% if user_signed_in? %>
          <li class="nav-item nav-link"><%= link_to "Annuaire", users_path %></li>
        <% else %>
          <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Annuaire</a>
        <% end %>

        <% if user_signed_in? %>
          <li class="nav-item nav-link"><%= link_to "Annonces", posts_path %></li>
        <% else %>
          <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Annonces</a>
        <% end %>

        <% if user_signed_in? %>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarScrollingDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Profil
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarScrollingDropdown">
              <li class="dropdown-item">Salut <%= current_user.first_name.capitalize %></li>
              <li class="dropdown-item"><%= link_to "Se déconnecter", destroy_user_session_path, method: :delete %></li>
              <li><hr class="dropdown-divider"></li>
              <li class="dropdown-item"><%= link_to 'Mon espace', user_path(current_user) %></li>
              <!--
              <% if current_user_is_admin? %>
                <li class="dropdown-item"><%= link_to 'Admin', pages_admin_path %></li>
              <% end %>
              -->
              <li class="dropdown-item"><li><hr class="dropdown-divider"></li>
              <li class="dropdown-item"><%= link_to "Modifier email / mot de passe", edit_user_registration_path %></li>
            </ul>
          </li>
        <% else %>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarScrollingDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Se connecter
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarScrollingDropdown">
              <li class="dropdown-item"><%= link_to "Se connecter", new_user_session_path %></li>
              <li class="dropdown-item"><%= link_to "S'inscrire", new_guest_path %></li>
            </ul>
          </li>
        <% end %>

      </ul>

    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RenovBlog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link rel="preconnect" href="https://fonts.googleapis.com"> 
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>

    <!-- FONT AWESOME -->
    <script src="https://kit.fontawesome.com/030dab100e.js" crossorigin="anonymous"></script><!-- avec mon given code -->

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <script src="https://use.fontawesome.com/releases/v5.13.0/js/all.js"></script>

    <!-- GOOGLE ICON -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <!-- GOOGLE FONT -->
    <link href="https://fonts.googleapis.com/css2?family=Roboto&display=swap" rel="stylesheet">

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css">
    
  </head>

  <body>
    <%= render "layouts/navbar" %>
    <%= render "layouts/flash" %>
    <%= yield %>
    <%= render "layouts/footer" %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/admin.html.erb
<div class="container">

  <h1>Demande de membre</h1>

  <% if is_member_request? %>
    <table>
      <tr>
        <th>prénom</th>
        <th>nom de famille</th>
        <th>email</th>
        <th>téléphone</th>
        <th></th>
      </tr>

      <% @guests.each do |guest| %>
        <tr>
          <td style="width:20%"><%= guest.first_name.capitalize %></td>
          <td style="width:20%"><%= guest.last_name.capitalize %></td>
          <td style="width:20%"><%= guest.email %></td>
          <td style="width:20%"><%= guest.phone_number %></td>
          <td style="width:20%">
            <%= link_to 'valider la demande', confirm_guest_to_user_page_path(guest.id), method: 'post' %> | 
            <%= link_to 'refuser la demande', refuse_guest_page_path(guest.id), method: 'post', data: { confirm: 'Êtes vous certain de vouloir refuser cette demande ?' } %> | 
          envoie email 
          </td>
        </tr>
      <% end %>
    </table>
  <% else %>
    <p>
      Auncune demande en attente
    </p>
  <% end %>


  <br>
  <hr>
  <br>

   <h1>Annuaire des membres</h1>

  <div>
    <table>
      <tr>
        <th></th>
        <th><%= link_to "prénom", pages_admin_path(order: 'name') %></th>
        <th><%= link_to "nom de famille", pages_admin_path(order: 'lastname') %></th>
        <th>téléphone</th>
        <th>email</th>
        <th>création</th>
        <th>annnonce</th>
        <th></th>
      </tr>

      <% @users.each do |user| %>
        <tr>
          <td style="width:10%">
            <% if user.avatar.attached? %>
              <%= image_tag user.avatar.variant(resize_to_limit: [50, 50]) %>
            <% end %>
          </td>
          <td style="width:15%"><%= user.first_name.capitalize %></td>
          <td style="width:15%"><%= user.last_name.capitalize %></td>
          <td style="width:15%"><%= user.phone_number %></td>
          <td style="width:20%"><%= user.email %></td>
          <td style="width:15%"><%= user.posts.count %></td>
          <td style="width:15%"><%= user.articles.count %></td>
          <td><%= link_to 'voir', user_path(user) %></td>
        </tr>
      <% end %>
    </table>

    <br>


    <br>
    <hr>
    <br>
    
    <div>
      <%= link_to 'Enregister un nouveau membre', new_user_path %>
    </div>

  </div>

  <br>
  <hr>
  <br>

  <div>
    <ul>
      <li>il y a <%= number_of_members %> membres</li>
      <li>il y a <%= number_of_articles %> créations</li>
      <li>il y a <%= number_of_posts %> posts</li>
      <li>soit une moyenne de <%= number_of_articles / number_of_members %> créations postées par membres</li>
    </ul>
    <ul>
      <% @categories.each do |cat| %>
        <li><%= pluralize cat.articles.count, cat.name %></li>
      <% end %>
    </ul>
  </div>




  <p>
    https://www.clubchevry2.com/
  </p>

  <br>


</div>